version: "3.7"

services:
  progresstracker-backend:
    image: progresstracker-backend
    container_name: progresstracker-backend
    ports:
      - 5000:5000
networks:
  default:
    external: false
    name: progresstracker
